### ISSUE TITLE
Minimessage Support

### ISSUE THREAD

**Issue by TheZexquex** [Oribuin/EternalTags#11]
Hey, it would be cool if the plugin would also support [MiniMessage](https://github.com/KyoriPowered/adventure/tree/main/4/text-minimessage) formatting, since it is the new standard on paper servers.

**Comment by Oribuin** [comment]
I think this is definitely a possibility to look into, however the plugin was originally designed to use the HexUtils provided by [RoseGarden](https://github.com/Rosewood-Development/RoseGarden/blob/master/src/main/java/dev/rosewood/rosegarden/utils/HexUtils.java) So, itsn't high on my priorities

**Comment by Oribuin** [comment]
On ✨ Further ✨ exploration, MiniMessage is actually quite difficult to implement in the plugin if it wasn't built on using it in the first place and would require a complete switch up to how the language system functions
