### ISSUE TITLE
Unintuitive GUI behavior

### ISSUE THREAD

**Issue by UniqueUserName500** [Oribuin/EternalTags#12]
Can you make the GUI that when you click on the tag, it remove the tag rather than equip the tag again? or tell them that they cannot reequip the same tag

I know there is a clear tag button but it's unintuitive and confuse players.

Also when making addon for the plugin, it can lead to weird state so I have to becareful everytime I listen to the TagEquipEvent

Also why the TagUnequipEvent not give the Tag that's removed? Basically its some what useless

Thanks

**Comment by Oribuin** [comment]
I don't think a clear button is that confusing to me, nor is it to player, A. Button sets tag, B. Button clears tag, I'll add it but it'll be behind a config.yml option. (https://github.com/Oribuin/EternalTags/commit/f90eeee6318dfec5cfe0454de6db7629b42812f2, https://github.com/Oribuin/EternalTags/commit/ebe954b7f980e86cfbb032f68da5e371f052fb53, https://github.com/Oribuin/EternalTags/commit/b1c9d318a4bf12cd1bc2bada1f64fc8e24295a3b)
