### ISSUE TITLE
Can you support the title or mysql synchronization, otherwise you need to copy tag.yml to each sub-server every time, which is very troublesome

### ISSUE THREAD

**Issue by lizheyo77** [Oribuin/EternalTags#13]
Can you support the title or mysql synchronization, otherwise you need to copy tag.yml to each sub-server every time, which is very troublesome

**Comment by Oribuin** [comment]
Should be available in v1.1.5 (https://github.com/Oribuin/EternalTags/commit/d0500a7334d3e180f0eb886fe67c482b0d74e149)
