### ISSUE TITLE
1.20.6 Paper | Unintended Bold / Obfusicated Decoration not working

### ISSUE THREAD

**Issue by CaptnLucid** [Oribuin/EternalTags#40]
Methods to produce : I'll provide a custom example of a tag that I have on a server. `&#9B15CF&l✨&#9426D3&li&#8C36D7&lG&#8547DC&lo&#7D57E0&lo&#7668E4&lb&#6385E4&le&#4FA2E3&lr&#3CBEE3&li&#28DBE2&l✨&r&8]`

In this scenario, the ] at the end will still be bold, which isn't the desired effect, considering &r is typically used to reset formatting.

![Screenshot 2024-08-04 051411](https://github.com/user-attachments/assets/c8aec02c-6247-4187-b586-c08e8076c309)

The next issue is attempting to use &k on both of the i's, for vertical squiggles.

![Screenshot 2024-08-04 051510](https://github.com/user-attachments/assets/95241d4b-c646-4000-b642-a71b765c7435)

Is it intended for this to not be a feature?

**Comment by Oribuin** [comment]
Are you able to check if this issue persists on the latest release ?

**Comment by CaptnLucid** [comment]
> Are you able to check if this issue persists on the latest release ?

Can confirm that the issue is fixed in the latest release!
